# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  kaniko: 
    docker:
      - image: freeletics/kaniko-executor:latest

jobs:
  build:
    working_directory: ~/repo
    executor: kaniko
    steps: 
      - checkout
      - run:
          name: "kaniko build and publish api"
          shell: /bin/bash -eo pipefail
          command: |
            mkdir -p /kaniko/.docker
            auth=$(printf "${DOCKER_LOGIN}:${DOCKER_PASSWORD}" | base64)
            cat \<< JSON > /kaniko/.docker/config.json
            {
              "auths": {
                "https://index.docker.io/v1/": {
                  "auth": "${auth}"
                }
              }
            }
            JSON
            /kaniko/executor \
            --dockerfile "Dockerfile" \
            --context "." \
            --destination "doctori/opencycledatabase:latest"
  build_frontend:
    executor: kaniko
    steps: 
      - checkout
      - run:
          name: "kaniko build and publish frontend"
          shell: /bin/bash -eo pipefail
          command: |
            mkdir -p /kaniko/.docker
            auth=$(printf "${DOCKER_LOGIN}:${DOCKER_PASSWORD}" | base64)
            cat \<< JSON > /kaniko/.docker/config.json
            {
              "auths": {
                "https://index.docker.io/v1/": {
                  "auth": "${auth}"
                }
              }
            }
            JSON
            /kaniko/executor \
            --dockerfile "frontend/Dockerfile" \
            --context "frontend" \
            --destination "doctori/opencycledatabase-frontend:latest"

workflows:
  version: 2
  build:
    jobs:
      - build
      - build_frontend