# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  kaniko: 
    docker:
      - image: freeletics/kaniko-executor:latest

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Build app
          command: go build -o=ocd github.com/doctori/opencycledatabase/cmd/opencycledatabase
  build_frontend:
    executor: kaniko
    steps: 
      - checkout
      - run:
          name: "kaniko build and publish frontend"
          shell: /bin/bash -eo pipefail
          command: >-
            /kaniko/executor
            --dockerfile "Dockerfile"
            --context "frontend"
            --destination "doctori/opencycledatabase-frontend:latest"

workflows:
  version: 2
  build:
    jobs:
      - build
      - build_frontend